#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"

OUT_DIR="${OUT_DIR:-${REPO_ROOT}/results}"
CSV_PATH="${CSV_PATH:-${OUT_DIR}/neurips_baseline_manifest.csv}"
MD_PATH="${MD_PATH:-${OUT_DIR}/neurips_baseline_manifest.md}"

mkdir -p "${OUT_DIR}"

cat >"${CSV_PATH}" <<'CSV'
section,baseline_id,category,description,script,command_template,status
main,A5_full_pretrain_finetune,internal,Full CLD-Trans with Stage 1 checkpoint and fine-tuning,scripts/run_from_stage2.sh,STAGE1_CKPT=<path> MODE=fine_tune bash scripts/run_from_stage2.sh,implemented
main,A5_linear_probe,internal,Full CLD-Trans with frozen backbone and linear probe,scripts/run_ablation_studies.sh,STAGE1_CKPT=<path> bash scripts/run_ablation_studies.sh,implemented
ablation,A4_downstream_only,internal,No pretraining checkpoint downstream-only model,scripts/run_ablation_studies.sh,bash scripts/run_ablation_studies.sh,implemented
ablation,A_no_topk,internal,Disable top-k lag sparsification,scripts/run_ablation_studies.sh,bash scripts/run_ablation_studies.sh,implemented
ablation,A_ode_euler,internal,Replace ODE solver with Euler,scripts/run_ablation_studies.sh,bash scripts/run_ablation_studies.sh,implemented
transfer,few_shot_1_10_100,internal,Label-fraction transfer at 1/10/100 percent,scripts/run_from_stage2.sh,STAGE1_CKPT=<path> LABEL_FRACTIONS='1.0 0.1 0.01' bash scripts/run_from_stage2.sh,implemented
transfer,zero_shot_chbmit,internal,Zero-shot focal-lead localization on CHB-MIT,scripts/eval_zero_shot.sh,STAGE1_CKPT=<path> bash scripts/eval_zero_shot.sh,implemented
baseline,feature_linear,internal,Cheap handcrafted-feature linear classifier,scripts/run_feature_baselines_core.sh,bash scripts/run_feature_baselines_core.sh,implemented
external,InceptionTime,external,Published raw time-series CNN baseline from Fawaz et al. DMKD 2020,scripts/run_inceptiontime_baselines_core.sh,bash scripts/run_inceptiontime_baselines_core.sh,implemented
external,BIOT,external,Repo-native BIOT-style transformer baseline,scripts/run_external_baselines_core.sh,METHODS='BIOT' bash scripts/run_external_baselines_core.sh,implemented
external,BENDR,external,Repo-native BENDR-style temporal transformer baseline,scripts/run_external_baselines_core.sh,METHODS='BENDR' bash scripts/run_external_baselines_core.sh,implemented
external,EEG_GCNN,external,Repo-native EEG graph CNN baseline,scripts/run_external_baselines_core.sh,METHODS='EEG_GCNN' bash scripts/run_external_baselines_core.sh,implemented
external,DYNOTEARS,external,Repo-native lagged graph feature baseline inspired by DYNOTEARS,scripts/run_external_baselines_core.sh,METHODS='DYNOTEARS' bash scripts/run_external_baselines_core.sh,implemented
external,Rhino,external,Repo-native directional lagged graph feature baseline inspired by Rhino,scripts/run_external_baselines_core.sh,METHODS='Rhino' bash scripts/run_external_baselines_core.sh,implemented
tuning,hparam_quick,internal,Core hyperparameter sweep for NeurIPS response,scripts/run_hparam_sweep.sh,HPARAM_PRESET=quick STAGE1_CKPT=<path> bash scripts/run_hparam_sweep.sh,implemented
tuning,hparam_full,internal,Full hyperparameter sweep for camera-ready,scripts/run_hparam_sweep.sh,HPARAM_PRESET=full STAGE1_CKPT=<path> bash scripts/run_hparam_sweep.sh,implemented
CSV

cat >"${MD_PATH}" <<'MD'
# NeurIPS Baseline Manifest

This file is auto-generated by scripts/generate_baseline_manifest.sh.

## Scope

- Internal baselines and ablations currently implemented in this repo.
- External baselines listed in the paper plan and currently marked as pending.

## Internal Baselines (Implemented)

1. A5 full pretrain + fine-tune.
2. A5 linear probe.
3. A4 downstream-only (no pretrain checkpoint).
4. No top-k lag sparsification.
5. ODE solver Euler replacement.
6. Few-shot label fractions (1.0, 0.1, 0.01).
7. Zero-shot CHB-MIT focal-lead evaluation.
8. Feature-linear baseline on handcrafted waveform statistics.
9. InceptionTime published raw time-series CNN baseline.
10. BIOT-style transformer baseline.
11. BENDR-style temporal transformer baseline.
12. EEG-GCNN-style graph baseline.
13. DYNOTEARS-style lagged graph baseline.
14. Rhino-style directional lagged graph baseline.
15. Hyperparameter sweeps (quick and full presets).

## External Baselines (Implemented)

1. InceptionTime
2. BIOT-style
3. BENDR-style
4. EEG-GCNN-style
5. DYNOTEARS-style
6. Rhino-style
MD

echo "[ok] Wrote ${CSV_PATH}"
echo "[ok] Wrote ${MD_PATH}"
